apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: qms-observability
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
  type: ClusterIP
