apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: qms-observability
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.qms-observability.svc.cluster.local:9090
        isDefault: true
        editable: false
