apiVersion: v1
kind: Service
metadata:
  name: qms-backend
  labels:
    app: qms-backend
    component: api
spec:
  selector:
    app: qms-backend
    component: api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30040
  type: NodePort
