apiVersion: v1
kind: Secret
metadata:
  name: qms-backend-secret
type: Opaque
immutable: true
stringData:
  DATABASE_URL: postgresql://qmsadmin:<change-me>@qms-pg-sweden-41018.postgres.database.azure.com:5432/qms_db?sslmode=require
  JWT_SECRET: QMS_Local_2026!SuperSecureJwtSecret#42
