apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qms-production
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: qms-backend
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
