apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qms-staging
resources:
  - ../../base
patches:
  - target:
      kind: Service
      name: qms-backend
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
  - target:
      kind: Deployment
      name: qms-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/strategy/rollingUpdate/maxUnavailable
        value: 1
      - op: replace
        path: /spec/strategy/rollingUpdate/maxSurge
        value: 0
  - target:
      kind: HorizontalPodAutoscaler
      name: qms-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
